
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelBooking.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    public int Id { get; set; }

    public int RoomId { get; set; }

    public int StartDate { get; set; }

    public int EndDate { get; set; }

    public System.DateTime AddedUTC { get; set; }

}

}
